module org.eclipse.collections {
    requires jdk.unsupported;

    requires transitive org.eclipse.collections.api;

    exports org.eclipse.collections.impl;
    exports org.eclipse.collections.impl.bag;
    exports org.eclipse.collections.impl.bag.immutable;
    exports org.eclipse.collections.impl.bag.immutable.primitive;
    exports org.eclipse.collections.impl.bag.mutable;
    exports org.eclipse.collections.impl.bag.mutable.primitive;
    exports org.eclipse.collections.impl.bag.sorted.immutable;
    exports org.eclipse.collections.impl.bag.sorted.mutable;
    exports org.eclipse.collections.impl.bag.strategy.mutable;
    exports org.eclipse.collections.impl.bimap;
    exports org.eclipse.collections.impl.bimap.immutable;
    exports org.eclipse.collections.impl.bimap.mutable;
    exports org.eclipse.collections.impl.block.comparator;
    exports org.eclipse.collections.impl.block.comparator.primitive;
    exports org.eclipse.collections.impl.block.factory;
    exports org.eclipse.collections.impl.block.factory.primitive;
    exports org.eclipse.collections.impl.block.function;
    exports org.eclipse.collections.impl.block.function.checked;
    exports org.eclipse.collections.impl.block.function.primitive;
    exports org.eclipse.collections.impl.block.predicate;
    exports org.eclipse.collections.impl.block.predicate.checked;
    exports org.eclipse.collections.impl.block.predicate.primitive;
    exports org.eclipse.collections.impl.block.procedure;
    exports org.eclipse.collections.impl.block.procedure.checked;
    exports org.eclipse.collections.impl.block.procedure.checked.primitive;
    exports org.eclipse.collections.impl.block.procedure.primitive;
    exports org.eclipse.collections.impl.collection;
    exports org.eclipse.collections.impl.collection.immutable;
    exports org.eclipse.collections.impl.collection.mutable;
    exports org.eclipse.collections.impl.collection.mutable.primitive;
    exports org.eclipse.collections.impl.collector;
    exports org.eclipse.collections.impl.factory;
    exports org.eclipse.collections.impl.factory.primitive;
    exports org.eclipse.collections.impl.iterator;
    exports org.eclipse.collections.impl.lazy;
    exports org.eclipse.collections.impl.lazy.iterator;
    exports org.eclipse.collections.impl.lazy.parallel;
    exports org.eclipse.collections.impl.lazy.parallel.bag;
    exports org.eclipse.collections.impl.lazy.parallel.list;
    exports org.eclipse.collections.impl.lazy.parallel.set;
    exports org.eclipse.collections.impl.lazy.parallel.set.sorted;
    exports org.eclipse.collections.impl.lazy.primitive;
    exports org.eclipse.collections.impl.list;
    exports org.eclipse.collections.impl.list.fixed;
    exports org.eclipse.collections.impl.list.immutable;
    exports org.eclipse.collections.impl.list.immutable.primitive;
    exports org.eclipse.collections.impl.list.mutable;
    exports org.eclipse.collections.impl.list.mutable.primitive;
    exports org.eclipse.collections.impl.list.primitive;
    exports org.eclipse.collections.impl.map;
    exports org.eclipse.collections.impl.map.fixed;
    exports org.eclipse.collections.impl.map.immutable;
    exports org.eclipse.collections.impl.map.immutable.primitive;
    exports org.eclipse.collections.impl.map.mutable;
    exports org.eclipse.collections.impl.map.mutable.primitive;
    exports org.eclipse.collections.impl.map.ordered.mutable;
    exports org.eclipse.collections.impl.map.primitive;
    exports org.eclipse.collections.impl.map.sorted.immutable;
    exports org.eclipse.collections.impl.map.sorted.mutable;
    exports org.eclipse.collections.impl.map.strategy.immutable;
    exports org.eclipse.collections.impl.map.strategy.mutable;
    exports org.eclipse.collections.impl.multimap;
    exports org.eclipse.collections.impl.multimap.bag;
    exports org.eclipse.collections.impl.multimap.bag.sorted;
    exports org.eclipse.collections.impl.multimap.bag.sorted.immutable;
    exports org.eclipse.collections.impl.multimap.bag.sorted.mutable;
    exports org.eclipse.collections.impl.multimap.bag.strategy;
    exports org.eclipse.collections.impl.multimap.list;
    exports org.eclipse.collections.impl.multimap.set;
    exports org.eclipse.collections.impl.multimap.set.sorted;
    exports org.eclipse.collections.impl.multimap.set.strategy;
    exports org.eclipse.collections.impl.parallel;
    exports org.eclipse.collections.impl.partition.bag;
    exports org.eclipse.collections.impl.partition.bag.sorted;
    exports org.eclipse.collections.impl.partition.list;
    exports org.eclipse.collections.impl.partition.set;
    exports org.eclipse.collections.impl.partition.set.sorted;
    exports org.eclipse.collections.impl.partition.set.strategy;
    exports org.eclipse.collections.impl.partition.stack;
    exports org.eclipse.collections.impl.primitive;
    exports org.eclipse.collections.impl.set;
    exports org.eclipse.collections.impl.set.fixed;
    exports org.eclipse.collections.impl.set.immutable;
    exports org.eclipse.collections.impl.set.immutable.primitive;
    exports org.eclipse.collections.impl.set.mutable;
    exports org.eclipse.collections.impl.set.mutable.primitive;
    exports org.eclipse.collections.impl.set.primitive;
    exports org.eclipse.collections.impl.set.sorted.immutable;
    exports org.eclipse.collections.impl.set.sorted.mutable;
    exports org.eclipse.collections.impl.set.strategy.immutable;
    exports org.eclipse.collections.impl.set.strategy.mutable;
    exports org.eclipse.collections.impl.stack.immutable;
    exports org.eclipse.collections.impl.stack.immutable.primitive;
    exports org.eclipse.collections.impl.stack.mutable;
    exports org.eclipse.collections.impl.stack.mutable.primitive;
    exports org.eclipse.collections.impl.stack.primitive;
    exports org.eclipse.collections.impl.stream;
    exports org.eclipse.collections.impl.stream.primitive;
    exports org.eclipse.collections.impl.string.immutable;
    exports org.eclipse.collections.impl.tuple;
    exports org.eclipse.collections.impl.tuple.primitive;
    exports org.eclipse.collections.impl.utility;
    exports org.eclipse.collections.impl.utility.internal;
    exports org.eclipse.collections.impl.utility.internal.primitive;
    exports org.eclipse.collections.impl.utility.primitive;

    provides org.eclipse.collections.api.factory.bag.ImmutableBagFactory
        with org.eclipse.collections.impl.bag.immutable.ImmutableBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.MultiReaderBagFactory
        with org.eclipse.collections.impl.bag.mutable.MultiReaderMutableBagFactory;
    provides org.eclipse.collections.api.factory.bag.MutableBagFactory
        with org.eclipse.collections.impl.bag.mutable.MutableBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.ImmutableBooleanBagFactory
        with org.eclipse.collections.impl.bag.immutable.primitive.ImmutableBooleanBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.ImmutableByteBagFactory
        with org.eclipse.collections.impl.bag.immutable.primitive.ImmutableByteBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.ImmutableCharBagFactory
        with org.eclipse.collections.impl.bag.immutable.primitive.ImmutableCharBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.ImmutableDoubleBagFactory
        with org.eclipse.collections.impl.bag.immutable.primitive.ImmutableDoubleBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.ImmutableFloatBagFactory
        with org.eclipse.collections.impl.bag.immutable.primitive.ImmutableFloatBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.ImmutableIntBagFactory
        with org.eclipse.collections.impl.bag.immutable.primitive.ImmutableIntBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.ImmutableLongBagFactory
        with org.eclipse.collections.impl.bag.immutable.primitive.ImmutableLongBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.ImmutableShortBagFactory
        with org.eclipse.collections.impl.bag.immutable.primitive.ImmutableShortBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.MutableBooleanBagFactory
        with org.eclipse.collections.impl.bag.mutable.primitive.MutableBooleanBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.MutableByteBagFactory
        with org.eclipse.collections.impl.bag.mutable.primitive.MutableByteBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.MutableCharBagFactory
        with org.eclipse.collections.impl.bag.mutable.primitive.MutableCharBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.MutableDoubleBagFactory
        with org.eclipse.collections.impl.bag.mutable.primitive.MutableDoubleBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.MutableFloatBagFactory
        with org.eclipse.collections.impl.bag.mutable.primitive.MutableFloatBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.MutableIntBagFactory
        with org.eclipse.collections.impl.bag.mutable.primitive.MutableIntBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.MutableLongBagFactory
        with org.eclipse.collections.impl.bag.mutable.primitive.MutableLongBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.primitive.MutableShortBagFactory
        with org.eclipse.collections.impl.bag.mutable.primitive.MutableShortBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.sorted.ImmutableSortedBagFactory
        with org.eclipse.collections.impl.bag.sorted.immutable.ImmutableSortedBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bag.sorted.MutableSortedBagFactory
        with org.eclipse.collections.impl.bag.sorted.mutable.MutableSortedBagFactoryImpl;
    provides org.eclipse.collections.api.factory.bimap.ImmutableBiMapFactory
        with org.eclipse.collections.impl.bimap.immutable.ImmutableBiMapFactoryImpl;
    provides org.eclipse.collections.api.factory.bimap.MutableBiMapFactory
        with org.eclipse.collections.impl.bimap.mutable.MutableBiMapFactoryImpl;
    provides org.eclipse.collections.api.factory.list.FixedSizeListFactory
        with org.eclipse.collections.impl.list.fixed.FixedSizeListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.ImmutableListFactory
        with org.eclipse.collections.impl.list.immutable.ImmutableListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.MultiReaderListFactory
        with org.eclipse.collections.impl.list.mutable.MultiReaderMutableListFactory;
    provides org.eclipse.collections.api.factory.list.MutableListFactory
        with org.eclipse.collections.impl.list.mutable.MutableListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.ImmutableBooleanListFactory
        with org.eclipse.collections.impl.list.immutable.primitive.ImmutableBooleanListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.ImmutableByteListFactory
        with org.eclipse.collections.impl.list.immutable.primitive.ImmutableByteListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.ImmutableCharListFactory
        with org.eclipse.collections.impl.list.immutable.primitive.ImmutableCharListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.ImmutableDoubleListFactory
        with org.eclipse.collections.impl.list.immutable.primitive.ImmutableDoubleListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.ImmutableFloatListFactory
        with org.eclipse.collections.impl.list.immutable.primitive.ImmutableFloatListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.ImmutableIntListFactory
        with org.eclipse.collections.impl.list.immutable.primitive.ImmutableIntListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.ImmutableLongListFactory
        with org.eclipse.collections.impl.list.immutable.primitive.ImmutableLongListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.ImmutableShortListFactory
        with org.eclipse.collections.impl.list.immutable.primitive.ImmutableShortListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.MutableBooleanListFactory
        with org.eclipse.collections.impl.list.mutable.primitive.MutableBooleanListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.MutableByteListFactory
        with org.eclipse.collections.impl.list.mutable.primitive.MutableByteListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.MutableCharListFactory
        with org.eclipse.collections.impl.list.mutable.primitive.MutableCharListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.MutableDoubleListFactory
        with org.eclipse.collections.impl.list.mutable.primitive.MutableDoubleListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.MutableFloatListFactory
        with org.eclipse.collections.impl.list.mutable.primitive.MutableFloatListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.MutableIntListFactory
        with org.eclipse.collections.impl.list.mutable.primitive.MutableIntListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.MutableLongListFactory
        with org.eclipse.collections.impl.list.mutable.primitive.MutableLongListFactoryImpl;
    provides org.eclipse.collections.api.factory.list.primitive.MutableShortListFactory
        with org.eclipse.collections.impl.list.mutable.primitive.MutableShortListFactoryImpl;
    provides org.eclipse.collections.api.factory.map.FixedSizeMapFactory
        with org.eclipse.collections.impl.map.fixed.FixedSizeMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.ImmutableMapFactory
        with org.eclipse.collections.impl.map.immutable.ImmutableMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.MutableMapFactory
        with org.eclipse.collections.impl.map.mutable.MutableMapFactoryImpl;
    // TODO
    // provides org.eclipse.collections.api.factory.map.primitive.ImmutableBooleanBooleanMapFactory
    //     with org.eclipse.collections.impl.map.immutable.primitive.ImmutableBooleanBooleanMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.ImmutableBooleanByteMapFactory
    //     with org.eclipse.collections.impl.map.immutable.primitive.ImmutableBooleanByteMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.ImmutableBooleanCharMapFactory
    //     with org.eclipse.collections.impl.map.immutable.primitive.ImmutableBooleanCharMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.ImmutableBooleanDoubleMapFactory
    //     with org.eclipse.collections.impl.map.immutable.primitive.ImmutableBooleanDoubleMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.ImmutableBooleanFloatMapFactory
    //     with org.eclipse.collections.impl.map.immutable.primitive.ImmutableBooleanFloatMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.ImmutableBooleanIntMapFactory
    //     with org.eclipse.collections.impl.map.immutable.primitive.ImmutableBooleanIntMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.ImmutableBooleanLongMapFactory
    //     with org.eclipse.collections.impl.map.immutable.primitive.ImmutableBooleanLongMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.ImmutableBooleanShortMapFactory
    //     with org.eclipse.collections.impl.map.immutable.primitive.ImmutableBooleanShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableByteBooleanMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableByteBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableByteByteMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableByteByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableByteCharMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableByteCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableByteDoubleMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableByteDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableByteFloatMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableByteFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableByteIntMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableByteIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableByteLongMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableByteLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableByteObjectMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableByteObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableByteShortMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableByteShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableCharBooleanMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableCharBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableCharByteMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableCharByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableCharCharMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableCharCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableCharDoubleMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableCharDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableCharFloatMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableCharFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableCharIntMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableCharIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableCharLongMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableCharLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableCharObjectMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableCharObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableCharShortMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableCharShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableDoubleBooleanMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableDoubleBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableDoubleByteMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableDoubleByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableDoubleCharMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableDoubleCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableDoubleDoubleMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableDoubleDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableDoubleFloatMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableDoubleFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableDoubleIntMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableDoubleIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableDoubleLongMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableDoubleLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableDoubleObjectMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableDoubleObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableDoubleShortMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableDoubleShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableFloatBooleanMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableFloatBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableFloatByteMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableFloatByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableFloatCharMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableFloatCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableFloatDoubleMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableFloatDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableFloatFloatMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableFloatFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableFloatIntMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableFloatIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableFloatLongMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableFloatLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableFloatObjectMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableFloatObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableFloatShortMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableFloatShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableIntBooleanMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableIntBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableIntByteMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableIntByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableIntCharMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableIntCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableIntDoubleMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableIntDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableIntFloatMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableIntFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableIntIntMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableIntIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableIntLongMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableIntLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableIntObjectMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableIntObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableIntShortMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableIntShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableLongBooleanMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableLongBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableLongByteMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableLongByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableLongCharMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableLongCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableLongDoubleMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableLongDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableLongFloatMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableLongFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableLongIntMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableLongIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableLongLongMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableLongLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableLongObjectMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableLongObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableLongShortMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableLongShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableObjectBooleanMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableObjectBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableObjectByteMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableObjectByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableObjectCharMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableObjectCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableObjectDoubleMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableObjectDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableObjectFloatMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableObjectFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableObjectIntMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableObjectIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableObjectLongMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableObjectLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableObjectShortMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableObjectShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableShortBooleanMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableShortBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableShortByteMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableShortByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableShortCharMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableShortCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableShortDoubleMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableShortDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableShortFloatMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableShortFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableShortIntMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableShortIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableShortLongMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableShortLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableShortObjectMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableShortObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.ImmutableShortShortMapFactory
        with org.eclipse.collections.impl.map.immutable.primitive.ImmutableShortShortMapFactoryImpl;
    // TODO
    // provides org.eclipse.collections.api.factory.map.primitive.MutableBooleanBooleanMapFactory
    //     with org.eclipse.collections.impl.map.mutable.primitive.MutableBooleanBooleanMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.MutableBooleanByteMapFactory
    //     with org.eclipse.collections.impl.map.mutable.primitive.MutableBooleanByteMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.MutableBooleanCharMapFactory
    //     with org.eclipse.collections.impl.map.mutable.primitive.MutableBooleanCharMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.MutableBooleanDoubleMapFactory
    //     with org.eclipse.collections.impl.map.mutable.primitive.MutableBooleanDoubleMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.MutableBooleanFloatMapFactory
    //     with org.eclipse.collections.impl.map.mutable.primitive.MutableBooleanFloatMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.MutableBooleanIntMapFactory
    //     with org.eclipse.collections.impl.map.mutable.primitive.MutableBooleanIntMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.MutableBooleanLongMapFactory
    //     with org.eclipse.collections.impl.map.mutable.primitive.MutableBooleanLongMapFactoryImpl;
    // provides org.eclipse.collections.api.factory.map.primitive.MutableBooleanShortMapFactory
    //     with org.eclipse.collections.impl.map.mutable.primitive.MutableBooleanShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableByteBooleanMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableByteBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableByteByteMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableByteByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableByteCharMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableByteCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableByteDoubleMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableByteDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableByteFloatMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableByteFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableByteIntMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableByteIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableByteLongMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableByteLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableByteObjectMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableByteObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableByteShortMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableByteShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableCharBooleanMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableCharBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableCharByteMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableCharByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableCharCharMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableCharCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableCharDoubleMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableCharDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableCharFloatMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableCharFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableCharIntMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableCharIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableCharLongMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableCharLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableCharObjectMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableCharObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableCharShortMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableCharShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableDoubleBooleanMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableDoubleBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableDoubleByteMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableDoubleByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableDoubleCharMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableDoubleCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableDoubleDoubleMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableDoubleDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableDoubleFloatMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableDoubleFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableDoubleIntMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableDoubleIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableDoubleLongMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableDoubleLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableDoubleObjectMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableDoubleObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableDoubleShortMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableDoubleShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableFloatBooleanMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableFloatBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableFloatByteMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableFloatByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableFloatCharMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableFloatCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableFloatDoubleMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableFloatDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableFloatFloatMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableFloatFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableFloatIntMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableFloatIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableFloatLongMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableFloatLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableFloatObjectMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableFloatObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableFloatShortMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableFloatShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableIntBooleanMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableIntBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableIntByteMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableIntByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableIntCharMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableIntCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableIntDoubleMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableIntDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableIntFloatMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableIntFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableIntIntMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableIntIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableIntLongMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableIntLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableIntObjectMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableIntObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableIntShortMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableIntShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableLongBooleanMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableLongBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableLongByteMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableLongByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableLongCharMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableLongCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableLongDoubleMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableLongDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableLongFloatMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableLongFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableLongIntMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableLongIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableLongLongMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableLongLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableLongObjectMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableLongObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableLongShortMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableLongShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectBooleanHashingStrategyMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectBooleanHashingStrategyMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectBooleanMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectByteHashingStrategyMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectByteHashingStrategyMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectByteMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectCharHashingStrategyMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectCharHashingStrategyMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectCharMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectDoubleHashingStrategyMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectDoubleHashingStrategyMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectDoubleMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectFloatHashingStrategyMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectFloatHashingStrategyMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectFloatMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectIntHashingStrategyMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectIntHashingStrategyMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectIntMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectLongHashingStrategyMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectLongHashingStrategyMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectLongMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectShortHashingStrategyMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectShortHashingStrategyMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableObjectShortMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableObjectShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableShortBooleanMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableShortBooleanMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableShortByteMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableShortByteMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableShortCharMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableShortCharMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableShortDoubleMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableShortDoubleMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableShortFloatMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableShortFloatMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableShortIntMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableShortIntMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableShortLongMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableShortLongMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableShortObjectMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableShortObjectMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.primitive.MutableShortShortMapFactory
        with org.eclipse.collections.impl.map.mutable.primitive.MutableShortShortMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.sorted.ImmutableSortedMapFactory
        with org.eclipse.collections.impl.map.sorted.immutable.ImmutableSortedMapFactoryImpl;
    provides org.eclipse.collections.api.factory.map.sorted.MutableSortedMapFactory
        with org.eclipse.collections.impl.map.sorted.mutable.MutableSortedMapFactoryImpl;
    provides org.eclipse.collections.api.factory.set.FixedSizeSetFactory
        with org.eclipse.collections.impl.set.fixed.FixedSizeSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.ImmutableSetFactory
        with org.eclipse.collections.impl.set.immutable.ImmutableSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.MultiReaderSetFactory
        with org.eclipse.collections.impl.set.mutable.MultiReaderMutableSetFactory;
    provides org.eclipse.collections.api.factory.set.MutableSetFactory
        with org.eclipse.collections.impl.set.mutable.MutableSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.ImmutableBooleanSetFactory
        with org.eclipse.collections.impl.set.immutable.primitive.ImmutableBooleanSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.ImmutableByteSetFactory
        with org.eclipse.collections.impl.set.immutable.primitive.ImmutableByteSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.ImmutableCharSetFactory
        with org.eclipse.collections.impl.set.immutable.primitive.ImmutableCharSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.ImmutableDoubleSetFactory
        with org.eclipse.collections.impl.set.immutable.primitive.ImmutableDoubleSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.ImmutableFloatSetFactory
        with org.eclipse.collections.impl.set.immutable.primitive.ImmutableFloatSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.ImmutableIntSetFactory
        with org.eclipse.collections.impl.set.immutable.primitive.ImmutableIntSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.ImmutableLongSetFactory
        with org.eclipse.collections.impl.set.immutable.primitive.ImmutableLongSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.ImmutableShortSetFactory
        with org.eclipse.collections.impl.set.immutable.primitive.ImmutableShortSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.MutableBooleanSetFactory
        with org.eclipse.collections.impl.set.mutable.primitive.MutableBooleanSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.MutableByteSetFactory
        with org.eclipse.collections.impl.set.mutable.primitive.MutableByteSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.MutableCharSetFactory
        with org.eclipse.collections.impl.set.mutable.primitive.MutableCharSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.MutableDoubleSetFactory
        with org.eclipse.collections.impl.set.mutable.primitive.MutableDoubleSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.MutableFloatSetFactory
        with org.eclipse.collections.impl.set.mutable.primitive.MutableFloatSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.MutableIntSetFactory
        with org.eclipse.collections.impl.set.mutable.primitive.MutableIntSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.MutableLongSetFactory
        with org.eclipse.collections.impl.set.mutable.primitive.MutableLongSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.primitive.MutableShortSetFactory
        with org.eclipse.collections.impl.set.mutable.primitive.MutableShortSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.sorted.ImmutableSortedSetFactory
        with org.eclipse.collections.impl.set.sorted.immutable.ImmutableSortedSetFactoryImpl;
    provides org.eclipse.collections.api.factory.set.sorted.MutableSortedSetFactory
        with org.eclipse.collections.impl.set.sorted.mutable.MutableSortedSetFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.ImmutableStackFactory
        with org.eclipse.collections.impl.stack.immutable.ImmutableStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.MutableStackFactory
        with org.eclipse.collections.impl.stack.mutable.MutableStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.ImmutableBooleanStackFactory
        with org.eclipse.collections.impl.stack.immutable.primitive.ImmutableBooleanStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.ImmutableByteStackFactory
        with org.eclipse.collections.impl.stack.immutable.primitive.ImmutableByteStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.ImmutableCharStackFactory
        with org.eclipse.collections.impl.stack.immutable.primitive.ImmutableCharStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.ImmutableDoubleStackFactory
        with org.eclipse.collections.impl.stack.immutable.primitive.ImmutableDoubleStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.ImmutableFloatStackFactory
        with org.eclipse.collections.impl.stack.immutable.primitive.ImmutableFloatStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.ImmutableIntStackFactory
        with org.eclipse.collections.impl.stack.immutable.primitive.ImmutableIntStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.ImmutableLongStackFactory
        with org.eclipse.collections.impl.stack.immutable.primitive.ImmutableLongStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.ImmutableShortStackFactory
        with org.eclipse.collections.impl.stack.immutable.primitive.ImmutableShortStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.MutableBooleanStackFactory
        with org.eclipse.collections.impl.stack.mutable.primitive.MutableBooleanStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.MutableByteStackFactory
        with org.eclipse.collections.impl.stack.mutable.primitive.MutableByteStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.MutableCharStackFactory
        with org.eclipse.collections.impl.stack.mutable.primitive.MutableCharStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.MutableDoubleStackFactory
        with org.eclipse.collections.impl.stack.mutable.primitive.MutableDoubleStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.MutableFloatStackFactory
        with org.eclipse.collections.impl.stack.mutable.primitive.MutableFloatStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.MutableIntStackFactory
        with org.eclipse.collections.impl.stack.mutable.primitive.MutableIntStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.MutableLongStackFactory
        with org.eclipse.collections.impl.stack.mutable.primitive.MutableLongStackFactoryImpl;
    provides org.eclipse.collections.api.factory.stack.primitive.MutableShortStackFactory
        with org.eclipse.collections.impl.stack.mutable.primitive.MutableShortStackFactoryImpl;

}
